name: Index data to opensearch cluster

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:   
  deploy-nightly-plyaground:
    strategy:
      matrix:
        dist_version: ['2.14.0', '3.0.0']
    uses: opensearch-project/opensearch-devops/.github/workflows/deploy-nightly-playground.yml@main
    with:
      dist_version: ${{ matrix.dist_version }}